name: vpatient
description: Virtual patient app that allows nurses to get experience in
  practical applications of patient care

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  another_flutter_splash_screen: ^1.1.3
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^0.13.5
  jwt_decode: ^0.3.1
  sliding_up_panel: ^2.0.0+1
  simple_form_builder: 
    git: 
      url: https://github.com/idriscanbolukbasi/SimpleFormBuilder.git

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/vpatient-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/avatars/
    - assets/images/landing_page/
    - assets/images/icons/
