name: vpatient
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.1
  google_sign_in: ^5.4.2
  flutter_native_splash: ^2.2.13

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/icons/vpatient-logo.png

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/images/icons/vpatient-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
