// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7x-onACFKplqclDTP-CAdvHgdLEakZdg',
    appId: '1:168069773129:web:8cfcb1d5ec36651564cc98',
    messagingSenderId: '168069773129',
    projectId: 'vpatient',
    authDomain: 'vpatient.firebaseapp.com',
    storageBucket: 'vpatient.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNW5ZIw07bGQJGbAORDs24a9zjc3lb1U',
    appId: '1:168069773129:android:f9f9023c9e677a3864cc98',
    messagingSenderId: '168069773129',
    projectId: 'vpatient',
    storageBucket: 'vpatient.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCJE2fnvdW5h1vjXzIzNQqdTcq8FxMDk',
    appId: '1:168069773129:ios:bbe1ce5134b1314564cc98',
    messagingSenderId: '168069773129',
    projectId: 'vpatient',
    storageBucket: 'vpatient.appspot.com',
    iosClientId: '168069773129-fb96pbke4rka2b58mn60a2p9m6iuqdhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.vpatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxCJE2fnvdW5h1vjXzIzNQqdTcq8FxMDk',
    appId: '1:168069773129:ios:bbe1ce5134b1314564cc98',
    messagingSenderId: '168069773129',
    projectId: 'vpatient',
    storageBucket: 'vpatient.appspot.com',
    iosClientId: '168069773129-fb96pbke4rka2b58mn60a2p9m6iuqdhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.vpatient',
  );
}
